"""
Django settings for share2teach project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import pyodbc
import os, sys
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#+7y9u^t#ygb#nz)-8gua5f13(xz5!tiylkt_8pzdg_q=a38we'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'

AUTH_USER_MODEL = "authentication.User"

LOGIN_URL = "/auth/login"
ADMIN_LOGIN_URL = "/admin/auth/login"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base.apps.BaseConfig',
    'faq',
    'authentication',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'storages',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'share2teach.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'share2teach.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",  # Your frontend domain
    # Add other domains if needed
]


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

"""DATABASES = {
'''DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',  # Or 'django.db.backends.postgresql', depending on your Azure database type
        'NAME': 'Share2Teach-db',          # Your Azure database name
        'USER': 'anbu',               # Your Azure SQL Database username
        'PASSWORD': 'Black0ps',           # Your Azure SQL Database password
        'HOST': 'anbu-server.database.windows.net',  # Azure database server URL
        'PORT': '',                        # Default MySQL port (or another if using a different database)
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',}
    }
}'''

DATABASES = {
    'default' :{
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'django_debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


# settings.py
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', 
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'base\static')]
'''STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'''

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

EMAIL_FROM_USER = 'thespectrumstore21@gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = EMAIL_FROM_USER
EMAIL_HOST_PASSWORD = 'jznm vfdj dgtc xbhj'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
FRONTEND_URL = 'http://127.0.0.1:8000'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#For upload files
import os #For upload files
MEDIA_URL = '/media/' #For upload files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') #For upload files

# code to connect database to file storage
AZURE_CONNECTION_STRING = 'DefaultEndpointsProtocol=https;AccountName=anbublackops;AccountKey=ydHHH//XnwTrsi8D89Jhw/V+bp0hsCtPADHGE1PFLeJ+ldRgW9MigDeOsWau3pofxyPfYKwpTskE+AStF/dVaw==;EndpointSuffix=core.windows.net'
AZURE_SHARE_NAME = 'anbu-fileshare'

# Azure Storage settings
AZURE_ACCOUNT_NAME = 'anbublackops'  # Azure Storage account name
AZURE_ACCOUNT_KEY = 'ydHHH//XnwTrsi8D89Jhw/V+bp0hsCtPADHGE1PFLeJ+ldRgW9MigDeOsWau3pofxyPfYKwpTskE+AStF/dVaw=='    # Azure Storage account key
AZURE_CONTAINER = 'uploads'   # Name of the container for file storage

# Configure Django's default file storage to use Azure
DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'

ORACLE_HOST = '127.0.0.1'
ORACLE_PORT = '1521'
ORACLE_SERVICE_NAME = 'XE'
ORACLE_USERNAME = 'anbu'
ORACLE_PASSWORD = 'cmpg'
