# Generated by Django 4.2.3 on 2024-08-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('educator', 'Educator'), ('moderator', 'Moderator')], default='educator', max_length=20),
        ),
    ]
