# Generated by Django 5.1.1 on 2024-09-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_affiliation_user_subject_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='subjects',
            field=models.ManyToManyField(related_name='moderators', to='authentication.subject'),
        ),
    ]
