# Generated by Django 5.1.1 on 2024-09-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_moderator_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='profile_picture',
        ),
    ]
