# Generated by Django 5.1.1 on 2024-09-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_subject_grade_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
    ]
