# Generated by Django 5.1 on 2024-09-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userfile'),
        ('authentication', '0009_remove_subject_grade'),
    ]

    operations = [
    ]
