# Generated by Django 5.1.1 on 2024-09-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_merge_0006_userfile_0009_remove_subject_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
