# Generated by Django 4.2.3 on 2024-08-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
