# Generated by Django 4.2.3 on 2024-08-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contributor_uploadedfile'),
        ('base', '0005_delete_subject'),
    ]

    operations = [
    ]
