# Generated by Django 5.1 on 2024-09-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_document_subject_report_message_document_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDemo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
