# Generated by Django 5.1 on 2024-09-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_document_subject_report_message_document_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploader',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
