# Generated by Django 5.1.1 on 2024-09-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_document_subject_report_message_document_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
