# Generated by Django 5.1.1 on 2024-09-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_document_subject_document_avg_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='report',
            name='reported_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
