# Generated by Django 5.1 on 2024-09-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_subjects'),
        ('base', '0008_usersdemo'),
        ('base', '0009_alter_uploadedfile_uploader'),
    ]

    operations = [
    ]
