# Generated by Django 5.1 on 2024-09-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_subjects'),
        ('base', '0008_usersdemo'),
        ('base', '0009_alter_uploadedfile_uploader'),
        ('base', '0010_remove_report_submitted_by_report_reported_by'),
    ]

    operations = [
    ]
