# Generated by Django 5.1.1 on 2024-09-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_merge_20240920_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='UsersDemo',
        ),
    ]
