# Generated by Django 5.1 on 2024-09-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_delete_subjects_delete_usersdemo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='email',
        ),
        migrations.AddField(
            model_name='contributor',
            name='bio',
            field=models.TextField(default='No bio available for this contributor.'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='image',
            field=models.ImageField(default='contributors/default.jpg', upload_to='contributors/'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='role',
            field=models.CharField(blank=True, default='Contributor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(default='Anonymous Contributor', max_length=100),
        ),
    ]
