# Generated by Django 5.1 on 2024-09-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_contributor_email_contributor_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
