# Generated by Django 5.1 on 2024-09-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_uploadedfile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
