# Generated by Django 5.1.1 on 2024-09-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_document_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
