# Generated by Django 5.1 on 2024-09-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_oerresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OERResource',
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(default=1, help_text='Comma-separated tags', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
