# Generated by Django 5.1.1 on 2024-09-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
